steps:
# Execute APP Engine Deployment
- name: 'gcr.io/cloud-builders/mvn:appengine'
  id: deploy-app-engine-compras-servicios
  args: ["-D", "skipTests", "clean", "package", "appengine:deploy","-P${_ENV}","-Dapp.stage.appEngineDirectory=src/main/appengine/${_ENV}"]

   
options:
   substitution_option: 'ALLOW_LOOSE'